apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: endgame-mcm-hd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 35Gi
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: endgame-mcm
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: endgame
    spec:
      domain:
        devices:
          disks:
          - bootOrder: 2
            cdrom:
              bus: sata
            name: cdromiso
          - bootOrder: 1
            disk:
              bus: virtio
            name: endgame-mcm-hd
        machine:
          type: q35
        resources:
          requests:
            memory: 4G
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: endgame-iso
      - name: endgame-mcm-hd
        persistentVolumeClaim:
          claimName: endgame-mcm-hd

